In [1]:
## Import Libraries

In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [3]:
## Load The Dataset

In [7]:
df = pd.read_csv("IMDb Movies India.csv", encoding='latin1')

In [8]:
df.head()

,Name,Year,Duration,Genre,Rating,Votes,Director,Actor 1,Actor 2,Actor 3
0,,NaN,NaN,Drama,NaN,NaN,J.S. Randhawa,Manmauji,Birbal,Rajendra Bhatia
1,#Gadhvi (He thought he was Gandhi),(2019),109 min,Drama,7.0,8,Gaurav Bakshi,Rasika Dugal,Vivek Ghamande,Arvind Jangid
2,#Homecoming,(2021),90 min,"Drama, Musical",NaN,NaN,Soumyajit Majumdar,Sayani Gupta,Plabita Borthakur,Roy Angana
3,#Yaaram,(2019),110 min,"Comedy, Romance",4.4,35,Ovais Khan,Prateik,Ishita Raj,Siddhant Kapoor
4,...And Once Again,(2010),105 min,Drama,NaN,NaN,Amol Palekar,Rajat Kapoor,Rituparna Sengupta,Antara Mali

In [9]:
## Exploring DataSet

In [10]:
df.shape

(15509, 10)

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15509 entries, 0 to 15508
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      15509 non-null  object
 1   Year      14981 non-null  object
 2   Duration  7240 non-null   object
 3   Genre     13632 non-null  object
 4   Rating    7919 non-null   float64
 5   Votes     7920 non-null   object
 6   Director  14984 non-null  object
 7   Actor 1   13892 non-null  object
 8   Actor 2   13125 non-null  object
 9   Actor 3   12365 non-null  object
dtypes: float64(1), object(9)
memory usage: 1.2+ MB

In [12]:
df.describe()

            Rating
count  7919.000000
mean      5.841621
std       1.381777
min       1.100000
25%       4.900000
50%       6.000000
75%       6.800000
max      10.000000

In [14]:
df.isna().sum()

Name           0
Year         528
Duration    8269
Genre       1877
Rating      7590
Votes       7589
Director     525
Actor 1     1617
Actor 2     2384
Actor 3     3144
dtype: int64

In [15]:
df = df.dropna(subset=['Rating'])

In [16]:
df.shape

(7919, 10)

In [17]:
df.isna().sum()

Name           0
Year           0
Duration    2068
Genre        102
Rating         0
Votes          0
Director       5
Actor 1      125
Actor 2      200
Actor 3      292
dtype: int64

In [18]:
## Filling the Missing Values

In [19]:
df['Genre']=df['Genre'].fillna(df['Genre'].mode()[0])

In [20]:
df['Director'] = df['Director'].fillna(df['Director'].mode()[0])

In [21]:
df['Actor 1'] = df['Actor 1'].fillna(df['Actor 1'].mode()[0])
df['Actor 2'] = df['Actor 2'].fillna(df['Actor 2'].mode()[0])
df['Actor 3'] = df['Actor 3'].fillna(df['Actor 3'].mode()[0])

In [22]:
df['Duration'] = df['Duration'].fillna(df['Duration'].mode()[0])

In [23]:
df['Duration'] = df['Duration'].str.replace(' min', '')
df['Duration'] = df['Duration'].astype(int)

In [24]:
df['Year'].head()

1    (2019)
3    (2019)
5    (1997)
6    (2005)
8    (2012)
Name: Year, dtype: object

In [25]:
df['Year'] = df['Year'].str.replace('(', '', regex=False)
df['Year'] = df['Year'].str.replace(')', '', regex=False)

df['Year'] = df['Year'].astype(int)

In [26]:
df['Votes'].head()

1        8
3       35
5      827
6    1,086
8      326
Name: Votes, dtype: object

In [27]:
df['Votes'] = df['Votes'].str.replace(',', '')

df['Votes'] = df['Votes'].astype(int)

In [38]:
df.drop('Name', axis=1, inplace=True)

In [39]:
df.isna().sum()

Year        0
Duration    0
Genre       0
Rating      0
Votes       0
Director    0
Actor 1     0
Actor 2     0
Actor 3     0
dtype: int64

In [42]:
df.duplicated().sum()

np.int64(0)

In [43]:
df.drop_duplicates(inplace=True)

In [44]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['Genre'] = le.fit_transform(df['Genre'])
df['Director'] = le.fit_transform(df['Director'])
df['Actor 1'] = le.fit_transform(df['Actor 1'])
df['Actor 2'] = le.fit_transform(df['Actor 2'])
df['Actor 3'] = le.fit_transform(df['Actor 3'])

In [45]:
df.head()

   Year  Duration  Genre  Rating  Votes  Director  Actor 1  Actor 2  Actor 3
1  2019       109    268     7.0      8       811     1782     2814      377
3  2019       110    207     4.4     35      1749     1589      890     2572
5  1997       147    177     4.7    827      2005      508       85     2449
6  2005       142    331     7.4   1086      2643      931     1388     3029
8  2012        82    367     5.6    326       174     2520     1461     1205

In [46]:
X = df.drop('Rating', axis=1)
y = df['Rating']

In [47]:
from sklearn.model_selection import train_test_split

In [48]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [49]:
from sklearn.linear_model import LinearRegression

In [50]:
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [51]:
y_pred=model.predict(X_test)

In [52]:
y_pred

array([6.03877375, 5.44307302, 5.19424811, ..., 5.66128042, 5.78800502,
       5.66475371], shape=(1584,))

In [53]:
y_test

9456     3.3
14816    5.3
3213     5.7
3778     7.2
5775     3.5
        ...
2710     5.9
7536     5.8
15353    4.5
9942     5.0
8466     8.6
Name: Rating, Length: 1584, dtype: float64

In [54]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [55]:
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)
print("Mean Absolute Error:", mae)
print("Mean Squared Error:", mse)
print("Root Mean Squared Error:", rmse)
print("R2 Score:", r2)

Mean Absolute Error: 1.0348792540422824
Mean Squared Error: 1.6964811531089745
Root Mean Squared Error: 1.3024903658411353
R2 Score: 0.08994794953229579

In [56]:
comparison = pd.DataFrame({
    'Actual Rating': y_test,
    'Predicted Rating': y_pred
})

comparison.head(10)

       Actual Rating  Predicted Rating
9456             3.3          6.038774
14816            5.3          5.443073
3213             5.7          5.194248
3778             7.2          5.770264
5775             3.5          5.771339
12201            6.6          5.429069
13171            6.3          5.879621
4650             6.9          5.904534
8701             5.2          6.168097
4707             7.4          5.872280

# Conclusion

A Movie Rating Prediction model was developed using the Linear Regression algorithm.

The dataset was preprocessed by handling missing values, converting categorical variables into numerical values, and cleaning numerical features.

The model was evaluated using MAE, MSE, RMSE, and R² Score. The evaluation shows that the model can estimate movie ratings, although predicting movie ratings remains challenging due to many influencing factors that are not included in the dataset.

This project demonstrates the complete machine learning workflow, including data preprocessing, model training, prediction, and evaluation.